### ISSUE TITLE
shinyproxy on rancher

### ISSUE THREAD

**Issue by totoman858** [remche/zero-to-shinyproxy#11]
Hi remche,

I'm using rancher and often the deployment of shinyproxy using helm failed; the container refuse to start because of the following error 

Liveness probe failed: Get http://10.42.0.30:8080/actuator/health/liveness: dial tcp 10.42.0.30:8080: connect: connection refused

Sometimes the container finally started working but most of the time when I want to redeploy the container it's not working anymore. Rancher is running in my private network ; on my own servers

Please do you have any idea ?

cheers,

**Comment by remche** [comment]
ShinyProxy might be long to start, you can try to increase `proxy.livenessProbe.initialDelaySeconds` (default is 40).

**Comment by totoman858** [comment]
thanks a lot it's working with initialDelaySeconds 100 !!!

**Comment by remche** [comment]
Glad I could help !
Note that you can play with `proxy.resources.limits.cpu` to speed up start, too.
