### ISSUE TITLE
cannot get resource "pods/log" in API group ""

### ISSUE THREAD

**Issue by mmoisse** [remche/zero-to-shinyproxy#13]
With the current rbac authorization shinyproxy has insufficient rights to read the logs from the pods it created.
The following should be added to `shinyproxy/templates/rbac.yaml`

```
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods/log"]
    verbs: ["get"]
```

**Comment by remche** [comment]
fixed by 3e017a8 thanks !
