### ISSUE TITLE
configurable initialDelaySeconds on liveness and readyness checks

### ISSUE THREAD

**Issue by kfox1111** [remche/zero-to-shinyproxy#16]
We've seen times where it takes shinyproxy a long time to start, causing it to get stuck in a restart loop and never coming up. We need a way to configure initialDelaySeconds on the checks.

**Comment by remche** [comment]
You can configure liveness and readiness probes via `proxy.livenessProbe` and `proxy.readinessProbe`.

**Comment by kfox1111** [comment]
Oh, I missed that you could override the whole section. Thanks.
