### ISSUE TITLE
landing-page

### ISSUE THREAD

**Issue by kfox1111** [remche/zero-to-shinyproxy#17]
When I set the configuration option for landing-page for shinyproxy, the ingress also got written to redirect to prefix: /{{.Values.proxy.landing-page }} 

This though breaks the system if your using oidc authentication, as its strips those urls out. I think the ingress prefix needs to be configurable separately then the config option landing-page to shinyproxy.

**Comment by kfox1111** [comment]
I might be able to write a quick patch for this, but not clear how you would like it resolved. Should we keep the same behavior but allow an additional override of ingress.path to override the existing behavior if specified, or should we have an ingress.path that overrides it from being / always (ignores proxy.landing-page)?

**Comment by remche** [comment]
I would opt for the former as it does not introduce changes. Seems more flexible, too. What's you're take on that ?

**Comment by kfox1111** [comment]
Works for me.
