### ISSUE TITLE
deploying to a namespace other than default

### ISSUE THREAD

**Issue by wccropper** [remche/zero-to-shinyproxy#34]
I want to deploy to the shinyproxy namespace and keep all spawned pods in the same namespace. This works for the deployment but the apps fail to start as the code is looking for the default namespace

`Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:shinyproxy:shinyproxy" cannot create resource "pods" in API group "" in the namespace "default".
`

**Comment by remche** [comment]
For you defense it's not straightforward. Man should have to specify user's pod namespace only if it's different from Helm `.Release.Namespace`…
