### ISSUE TITLE
req. Please update Chart to 2.6.0 of ShinyProxy and add mini config.yml for the impatient ;-)

### ISSUE THREAD

**Issue by Wesseldr** [remche/zero-to-shinyproxy#46]
First of all, Thank you for your work..

- Little request, could you kick the version of shiny proxy from 2.5.0 to 2.6.0 (latest)
- and could you provide a minimal config.yaml that would start on a KinD (or any local k8s) just as start point :)
Many thanks in advance... (sorry for being lazy at this point, still learning this k8s stuff and KinD :-)

**Comment by remche** [comment]
@Wesseldr 

> Little request, could you kick the version of shiny proxy from 2.5.0 to 2.6.0 (latest)

Done !

> and could you provide a minimal config.yaml that would start on a KinD (or any local k8s) just as start point :)

`test-values.yaml` should work with KinD. You might need to override ingress.hosts if you don't want to tweak your `/etc/hosts` though : 

`helm upgrade --install shiny shinyproxy -f test-values.yaml --set ingress.hosts[0]=''`

**Comment by Wesseldr** [comment]
minicube starts up :-)
but need to killa bug with:
kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission

Then it starts up :-). Thanks
