### ISSUE TITLE
ClusterRole

### ISSUE THREAD

**Issue by kfox1111** [remche/zero-to-shinyproxy#65]
I've been using the chart in a namespace as a regular user, set to only watch the same namespace. Its been working until I just tried upgrading it. It broke due to there being a ClusterRole now and not a Role:

https://github.com/remche/zero-to-shinyproxy/blob/master/shinyproxy/templates/rbac.yaml#L6

Could this be reverted back to a regular Role or made configurable?

**Comment by remche** [comment]
@kfox1111 to be sure that I understand, is the issue due to your limited rights on the cluster (you cant set a `ClusterRole`).

**Comment by kfox1111** [comment]
Yes. Users with just role=admin on a namespace can no longer install the chart in their namespace.

**Comment by remche** [comment]
That was introduced by 02ce7249c0392b7cb62af98c36a613988d29cec5 and the need to spawn pods in another namespace. I agree that it was a dirty way to implement it, I will fix that.

**Comment by kfox1111** [comment]
Ah, I see. Thanks! :)
